networks:
    php-workbench:

services:
    workbench:
        image: ${WORKBENCH_IMAGE}
        volumes:
            - ./project:/var/www/project
        environment:
            APP_ENV: ${APP_ENV}
        networks:
            - php-workbench
